### ISSUE TITLE
Consider better field alignment in headers

### ISSUE THREAD

**Issue by pmai** [modelica/fmi-ls-bus#124]
Since the operations headers in the low-cut have now moved fairly far from the compact CAN/on-the-wire encoding, we might want to take care of better alignment of fields for common 32bit/64bit platforms; e.g. the current op header is 5 bytes long, which misaligns most of the rest of the operation arguments, especially the 32bit length/ID/... fields.

By re-arranging and/or sometimes enlarging/padding fields we could likely align common fields better fairly easily. Multiple buffers can be force-aligned to 32bit/64bit if we so choose.

Something to consider prior to finalizing the 1.0.0 release.

**Comment by msuevern** [comment]
We discussed the issue in the F2F meeting:
 
What was the motivation for the "better field alignment"? 
dSPACE investigated the effect of the proposed changes with regards to the performance, but could not see any differences.
Even changing the op-code to 32 bit would not prevent to use the "pack(1)" instruction while defining the LS-BUS data type.

**Comment by msuevern** [comment]
We will change the op-code to 32bit.
