### ISSUE TITLE
Why length of PDU and not length of payload?

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-ls-bus#143]
The current specification defines the length field of a message as the whole length of the message including the op-code field (1byte) and the length field (5 bytes).
Hence, even if the operation doesn't need any arguments the length value will be 5. 
Isn't it more common to just put the size of the payload in a payload length field which could be actually zero?

**Comment by bmenne-dspace** [comment]
Decision: Current situation is OK. We need not to change something.
