### ISSUE TITLE
Interval of output Clock in "low cut" example

### ISSUE THREAD

**Issue by paulfilip** [modelica/fmi-ls-bus#150]
In Ch. 5.4.2, there is an example for modelDescription.xml, which defines the following output clock:

> Clock name="Powertrain.Tx_Clock" valueReference="1004"
>         causality="output" variability="discrete" interval="aperiodic"

        
 According to the FMI standard, output clocks must have intervalVariability == triggered.
 Was it meant to be a variable with causality == input? or the correct interval(Variability) should be triggered?

**Comment by msuevern** [comment]
@paulfilip you are right, the causality in Ch. 5.4.2 must be “input” for interval="aperiodic" or “output” for interval="triggered". I would recommend using the pair causality="input" and interval="aperiodic" in the example, as the description of time-based clocks is less obvious.
