### ISSUE TITLE
Provide examples for the Sandbox before the Munich F2F Meeting

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-bus#157]
@ dspace-colleagues and others: could you please provide examples to the sanbox https://github.com/modelica/fmi-design/tree/ls-bus-sandbox some time before the F2F meeting in Munich? Together with referen solutions for the expected behaviour? (see discussionin today's design webmeeting: https://github.com/modelica/fmi-design/blob/master/Meetings/2024/2024-04-23-FMI-Design-Webmeeting/README.md#ls-bus)

- We plan to have a "mini plugfest" on Wednesday morning
- Several colleagues would likt to test the import before
- @PenndorfT will not be able to participate, but could do some tests with an import prototype before the meeting, he would be available for a webmeeting on Tuesday afternoonn

**Comment by bmenne-dspace** [comment]
Yes @chrbertsch, I will prepare the requested artifacts and provide them as soon as possible.

**Comment by bmenne-dspace** [comment]
@chrbertsch, @jan-ribbe, @masoud-najafi, @PenndorfT, @pmai, @klausschuch I added some demos. You will find them at: https://github.com/modelica/fmi-design/tree/ls-bus-sandbox/FMI-LS-BUS/sandbox

I will also try to upload reference files of the bus traffic next week. If there are any questions or wishes please contact me!

**Comment by bmenne-dspace** [comment]
@chrbertsch, @jan-ribbe, @masoud-najafi, @PenndorfT, @pmai, @klausschuch, @andreas-junghanns I updated the provided FMUs. For our ArFuelsys sample the FMUs print also the data to transmit to the FMI logging mechanism. So the data to transmit can be checked.

**Comment by masoud-najafi** [comment]
Hi @bmenne-dspace ,
I interconnected the FMUs and everything goes well and clocks are ticked. Can you share the log files to compare and check?
Thanks,
Masoud

**Comment by bmenne-dspace** [comment]
The FMUs log and outputs the frame data to transfer directly the FMI log mechanism @masoud-najafi. For example like:

[Controller/Sab_MsgSeverity_Info] Can_Write called with **ID 2147483668**, upper ID 0 and data length **2** with data **0:93 1:18** 2:204 3:204 4:204 5:204 6:204 7:204
[EngineModel/Sab_MsgSeverity_Info] Can_Write called with **ID 2147483669**, upper ID 0 and data length **8** with data **0:166 1:21 2:176 3:4 4:250 5:63 6:25 7:55** 

I´m sorry but currently there is no buslog file that I can directly attach.

**Comment by bmenne-dspace** [comment]
Close because demo FMus were delivered
