### ISSUE TITLE
Get Feedback from other domains besides automotive (aerospace, buildings, automatization)

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-bus#16]
Until now, the participants and use cases for this layered standard are very automotive centric.
However, the concepts are really generic and could be used totally different domains, that have similar network communication busses.
So it would be great to get feedback and pariticipation in this working group from other domains:
- aerospace
- buildings (BAC-net)
- automatization 
Please comment!

**Comment by bmenne-dspace** [comment]
Issue can be closed, because of no response from other problem domains.
