### ISSUE TITLE
Create v1.0.0-beta.1 release

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-bus#176]
Moving to the beta-phase was approved by the FMI Steering Committee meeting today.
@bmenne-dspace : could you please create take care of this?

**Comment by bmenne-dspace** [comment]
@chrbertsch yes I will take care of this. Thank you very much!

**Comment by bmenne-dspace** [comment]
@chrbertsch I created the beta.1 release and we can close this issue now.
