### ISSUE TITLE
list of simulator with LS-BUS support

### ISSUE THREAD

**Issue by PRAVEENFrmBOSCH** [modelica/fmi-ls-bus#185]
1) Documentation can list down the existing simulator that supports the LS BUS with all 3-architecture mentioned. 
2) Also a sample simulator fmpy python script to work with can-bus-simulation fmu and can-node-triggered-output fmu will be helpful to understand the flow.

**Comment by bmenne-dspace** [comment]
I think it's a great idea @PRAVEENFrmBOSCH. Maybe we could talk about it at the next FMI design meeting @chrbertsch?

**Comment by PRAVEENFrmBOSCH** [comment]
Meanwhile if you guys have sample simulator setup for the LS-BUS please share it with me.

**Comment by chrbertsch** [comment]
FMI Design Webmeeting
Benedikt: I can make a suggestion
Christian we should clearly mark, that the LS-BUS is unreleased; we should distinguish between prototype versions of tools (possibly with contact address) and released version of tools

**Comment by bmenne-dspace** [comment]
@klausschuch can you reveal how your FMU importer is called that you used for cross check? I don't know the correct name for the tool list (see suggestion above)

**Comment by bmenne-dspace** [comment]
@PRAVEENFrmBOSCH The list of simulators for FMI-LS-BUS can now be found within the GitHub landing page (see https://github.com/modelica/fmi-ls-bus#tools). @chrbertsch fyi
