### ISSUE TITLE
Inconsistent use naming convention for clock in high-cut uses naming convention, rest uses teminal member names

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-ls-bus#188]
After we decided to use terminals for ls-bus, we switched to use terminal member names for signals (see #162).
However, the current spec still requires that the clocks of the high-cut must follow a certain naming convention.
This is IMHO inconsistent and we should use the memberName attribute here as well.

**Comment by pmai** [comment]
I think this issue goes further, i.e. we currently also require common prefixes for the signal variable names in a PDU, which is also  redundant given the terminal information. As this unneccessarily restricts retrofitting bus support to existing models, I think this should be downgraded to, at most, a recommendation.
