### ISSUE TITLE
Wrong escaping character in mimeType in modelDescription.xml example

### ISSUE THREAD

**Issue by paulfilip** [modelica/fmi-ls-bus#196]
In the provided modelDescription.xml from Ch. 5.4.2, mimeType attributes of the Binary variables are defined as:
`mimeType="application/org.fmi-standard.fmi-ls-bus.can; version=&quot1.0.0-beta.1&quot"`

In order to specifiy a quotation mark, this should be `&quot; `

So, the correct form would be:
`mimeType="application/org.fmi-standard.fmi-ls-bus.can; version=&quot;1.0.0-beta.1&quot;"`

**Comment by bmenne-dspace** [comment]
@paulfilip yes you are right! Thanks for that hint! I will prepare a PR for that issue.
