### ISSUE TITLE
Changes to Direct Confirmation Parameter chapter

### ISSUE THREAD

**Issue by bmenne-dspace** [modelica/fmi-ls-bus#20]
1. The Direct Confirmation Parameter chapter shall be moved to the CAN specific document part, because the parameter description is only relevant in the CAN case.

2. The parameter shall be renamed to BusNotifications (Default false) to describe the meaning more precisely. Thus improves the reader's understanding.

3. The parameter name and content should be formulated more precisely. What information is important:

  - With CAN, a transmission is confirmed by at least one recipient. The Confirm operation simulates this behavior. Otherwise there is a bus error.
  - It is a design decision that the confirm operation is only generated by the Bus Simulation and not by Network FMUs.
  - The parameter defines the properties of the simulation environment.

From these points one can derive:

  - If DirectConfirmation is set to true, then the FMU must not wait for confirm operations.
  - The parameter is set by the importer.
  - No Bus Error, Arbitration Lost operations are sent to the Network FMUs either.

4. The phrase "...the confirmation of the transmitted network data shall be directly done by the sender itself." should be avoided. The Network FMU should be free to decide how to deal with the parameter internally.

This issue only relates to the wording and better reader's understanding. It does not change or extend the current behavior.

**Comment by bmenne-dspace** [comment]
dSPACE can take care of that issue.

**Comment by PTaeuberDS** [comment]
This issue is not solved by #21 and has to be rethought. dSPACE will provide a new solution in a new PR.
