### ISSUE TITLE
FMI-LS-BUS or fmi-ls-bus

### ISSUE THREAD

**Issue by bmenne-dspace** [modelica/fmi-ls-bus#200]
We should decide in the FMI Design meeting whether we want to write the layered standard in abbreviated capitals or in lowercase, i.e. FMI-LS-BUS or fmi-ls-bus. After we have made our decision, I would go through the entire document and the header files and adjust or straighten them out. At the moment we have a mix of both, which is a bit unfortunate.

**Comment by chrbertsch** [comment]
In the layered standard text, "fmi-ls-bus" seems only to be used in the reverse domain name notation. 
If we talk about the layered standard in some text (e.g. Webpage,  text in the header files, Powerpoint slides), I personally would write it in capital letters (as we also write "FMI Standard" with capital letters. Any other other opinions?

**Comment by bmenne-dspace** [comment]
> In the layered standard text, "fmi-ls-bus" seems only to be used in the reverse domain name notation. If we talk about the layered standard in some text (e.g. Webpage, text in the header files, Powerpoint slides), I personally would write it in capital letters (as we also write "FMI Standard" with capital letters. Any other other opinions?

Yes, with document I also mean the Impl. Guide for Bus. There we mentioned it explicit. 

I'm fine with both options. The idea behind this issue was just to have a decition before, so that there is no redundant work to fix the name over all relevant places.
