### ISSUE TITLE
Do we require a fixed memberName for high cut terminals?

### ISSUE THREAD

**Issue by klausschuch** [modelica/fmi-ls-bus#209]
The specification for the high cut currently says (4.4.2. Frame Terminal):
> There must be one <TerminalMemberVariable> for the Clock this frame is connected to. The memberName of this variable must be "Clock".

Do we really need to have to require a specific memberName ("Clock") or wouldn't just the requirement that there has to be exactly one clock in this terminal be enough?
As far as I see this is the only fixed memberName that we require right now.

**Comment by chrbertsch** [comment]
Pierre: I would not require to have exactly one clock. We could need other clocks in the future. We should not require to name it "clock". Could we use variableKind? We could give it a special variableKind?
Klaus: currently it is variableKind="signal", this is perhaps not good.
Pierre: We could give it a specific variableKind
