### ISSUE TITLE
Create a user/implementer's guide for LS-BUS

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-bus#23]
Repository name? https://github.com/modelica/fmi-guides/fmi-ls-bus ?

**Comment by bmenne-dspace** [comment]
The target shall be a sub directory within the existing FMI Guide Repo

**Comment by chrbertsch** [comment]
Done: https://github.com/modelica/fmi-guides/tree/main/ls-bus-guide

ToDo: Link the guide from the LS-BUS documentation, and move/add content there

**Comment by PTaeuberDS** [comment]
Since the repository is created now, dSPACE will take care of moving the "guiding parts" to the guide.
