### ISSUE TITLE
Extend Layered Standard Description in Manifest File

### ISSUE THREAD

**Issue by PTaeuberDS** [modelica/fmi-ls-bus#41]
In the manifest file there is a "description" attribute. Currently, it only says "Layered Standard for Bus". As this information will probably be displayed in the importing tools, we should provide a little bit more detail about the content of this layered standard.

E.g. something like: "Layered Standard for the signal or frame based network communication between FMUs. [...]"

**Comment by bmenne-dspace** [comment]
Will be already addressed and fixed in issue "Layered Standard Manifest File is missing for fmi-ls-bus" (see https://github.com/modelica/fmi-ls-bus/issues/24) --> Can be closed
