### ISSUE TITLE
Move headers and schema folders to the root level?

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-ls-bus#74]
... as in the fmi-standard repo. Or is there a reason why to have the them in the /docs folder?
Not urgent, we can do this after merging the PRs that are currently open

**Comment by bmenne-dspace** [comment]
@chrbertsch we just take the document structure from fmi-ls-xcp. But I´m fine with the idea of restructuring. As you already mentioned I can do it after merging the outstanding PRs.
