### ISSUE TITLE
<Annotation type="ECU" /> within High-Cut Bus Terminals 

### ISSUE THREAD

**Issue by bmenne-dspace** [modelica/fmi-ls-bus#85]
Within the High-Cut Bus Terminals uses Annotation:

![image](https://github.com/modelica/fmi-ls-bus/assets/18484379/a7af6412-81f9-4848-a95a-222eab789a84)

Within Low-Cut Bus Terminals uses no Annotation.  It shall be discussed if we need Annotation within High-Cut and decide if we also add it within Low-Cut. In my point of view it shall be equal. I think it is intended to distinguish bus terminals from other terminals in an FMU.

**Comment by bmenne-dspace** [comment]
I think we can discuss it during the next F2F meeting near Stuttgart.

**Comment by andreas-junghanns** [comment]
The annotation element describes which network node (or nodes) the vECU/plant model/rest-bus simulation implements.

Since the network description file is now optional, we need to make sure the text reflects that.
