### ISSUE TITLE
fmi-ls-bus headers are using C++11 feature: static_assert declaration

### ISSUE THREAD

**Issue by bmenne-dspace** [modelica/fmi-ls-bus#93]
The provided header files of the fmi-ls-bus is using C++11 static_assert declaration feature. For non C++11 compliant  compiler, this static check shall be easily switched off for the user of the header files. Switching on/off shall be realized within the headers by using conditional inclusion.

**Comment by ClemensB** [comment]
Just to clarify: The feature is also available in C11 (as alias to _Static_assert in assert.h) and beginning with C23 also as a keyword with the assert.h include.
But I still think it's a good idea to make the checks optional to support C99 as well.

**Comment by pmai** [comment]
> But I still think it's a good idea to make the checks optional to support C99 as well.

Exactly, I think the C11 dependency is more problematic than the C++11 dependency, as C11 support on pure C platforms is likely less widely supported than C++11 support on C++ platforms, and since it's only needed for the assert we can just conditionalyze it out...

**Comment by bmenne-dspace** [comment]
Exactly @pmai, we will fix that on dspace side and integrate it via this issue. I think at the beginning of the next week.
